version: '3'

services:

  application-nginx:
    image: cr.yandex/crp3vb48visoe0anu49g/nginx:dev
    restart: always
    ports:
      - "127.0.0.1:3080:80"
    links:
      - "application-fpm:php-fpm"

  application-fpm:
    image: cr.yandex/crp3vb48visoe0anu49g/php8.1-fpm:dev
    env_file: .env
    restart: always

  # Database -------------------------------------------------
  database:
    build:
      context: images/postgres
      dockerfile: Dockerfile
    container_name: ${BB_DATABASE_WORKDIR}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${PORT_POSTGRES}:5432'
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "3"
